### ISSUE TITLE
error update

### ISSUE THREAD

**Issue by pccheck** [s3inlc/hashtopussy#149]
Apply updates... Update Zap table... Fatal Error ! Database connection failed

sorry, how to?

**Comment by s3inlc** [comment]
It's really hard to see what the problem is here, with this information I can't work...
Please stick to the issue template and read what information would be nice to know for me to tell you more about the problem.

Just a wild guess, it could be that your MySQL server crashed because it was too much work for him. Did you crack a list with a lot of founds at once? Because in this case your hardware and MySQL configuration should be prepared for heavy load.

**Comment by pccheck** [comment]
I am reinstall server and database, is running ok

**Comment by pccheck** [comment]
how to update client?

I downloaded it
Access the update link on the server appears:
Apply updates ... Update Zap table ... OK Check csharp binary ... Update complete!
But in agent continues the old version


ID	Version	Programming Language	Operating Systems	Filename	 
1	0.43.12	csharp	                          Windows   hashtopussy.exe

**Comment by s3inlc** [comment]
There was a typo in the update script. You can change the version number on the 'Agent Binaries' page. Just enter 0.43.13 as version number there.

**Comment by pccheck** [comment]
I tried but it appears several times this screen in loop
E:\>hashtopussy.exe
Client Version 0.43.12
Cleaning up files post update
Checking for client updates
Downloading from http://192.168.10.46:8028/agents.php?download=1
Downloading 100% @ 8322,11 kb/s
Finished downloading latest client
Client will now relaunch

**Comment by s3inlc** [comment]
Are you sure you pulled all the updates from the repository and that your binary is not just still the old version?

**Comment by pccheck** [comment]
I downloaded it through github complete, copied all folder to / var / www / hashtopussy
I gave permission with chown
is necessary reinstall server?

**Comment by s3inlc** [comment]
No, there is no need to install it again.
Please just check again that your hashtopuss.exe file is the newest one. If it still does not work, post the loop from above with running in debug mode.

**Comment by pccheck** [comment]
in agent, download hashtopussy.exe, and after run, continue loop
its cretaed file HTPLauncherUpd.exe and run and Repeating several times
comand hahstopussy debug is same problem, continue in loop

**Comment by s3inlc** [comment]
I cannot help you anything if you don't provide me the debug output of the loop.

Run: ```hashtopussy.exe debug``` and then send me the output of the looping.

**Comment by pccheck** [comment]
E:\>hashtopussy.exe debug
Client Version 0.43.12
Cleaning up files post update
Checking for client updates
{"action":"update","type":"csharp","version":"0.43.12"}
{"action":"update","response":"SUCCESS","version":"NEW","url":"http:\/\/192.168.10.46:8028\/age
nts.php?download=1"}
Downloading from http://192.168.10.46:8028/agents.php?download=1
Downloading 100% @ 8113,29 kb/s
Finished downloading latest client
Client will now relaunch

E:\>

**Comment by s3inlc** [comment]
Can you please send me the md5 or sha1 sum of your hashtopussy.exe?

**Comment by pccheck** [comment]
hashtopussy debu is appear this message in top and open various prompts in loop infinite, I try record video and send

**Comment by s3inlc** [comment]
I really need to assume that you didn't update your hashtopussy correctly, as there are two people now which checked out static/hashtopussy.exe from the master branch and got the correct binary 0.43.13.

That's why I asked to provide me the checksum, so you can make sure that you got the latest version.
