### ISSUE TITLE
Getting Error when trying to crack with mode 1800

### ISSUE THREAD

**Issue by kawuum** [s3inlc/hashtopussy#245]
Hashtopussy version 0.3.2, hashcat version 3.6.0.

I was trying to crack a linux password using mode 1800. This works fine on hashcat (tried it standalone). If I try to crack it with hashtopussy, I get the following error:

"Use of --remove is not supported in native hashfile-format mode.". The same error appears when I manually start hashcat with mode 1800 and --remove parameter. Do you ave any advice on how to deal with this?

Thanks!

**Comment by s3inlc** [comment]
Is the hashlist you uploaded in a binary format?

**Comment by kawuum** [comment]
No, the hashlist is in textfile format.

I just found out how to solve the problem: Instead of using the whole line extracted from /etc/shadow, I need to remove username and some characters at the end (described here: https://samsclass.info/123/proj10/p12-hashcat.htm). If I do this, there is no error. 

Strange though, that it works using hashcat directly.

**Comment by s3inlc** [comment]
I'm not sure but there are some hash formats where hashcat is able to parse native hash files which contain more than just the hashes.

But generally when using a list of them and put them into Hashtopussy, make sure you just have the hashes in there as otherwise it might not be possible to remove them properly by hashcat.

**Comment by kawuum** [comment]
Cool, thanks!
