### ISSUE TITLE
Operation Timed Out

### ISSUE THREAD

**Issue by niels1189** [s3inlc/hashtopussy#254]
![image](https://user-images.githubusercontent.com/6758065/29164520-f5064f34-7dbf-11e7-9353-7a652f120c8b.png)

**Comment by niels1189** [comment]
Just outdated (bad queries). Fixed them.

**Comment by Thireus** [comment]
Hey @niels1189, what do you mean by bad queries? How did you fix your issue?

**Comment by winxp5421** [comment]
So I think what he means here ( I'm not 100% sure )

The client has a que based system and what I mean by that is if the server is unavailable or I/O locked due to heavy load the client will begin to save it's cracks and status updates untill the server is in an up state ( or not under heavy load). One normal operation is resumed server side the client will send the work it has done. This que system is persistent across client shutdowns just incase the client crashes or your hashtopussy.exe is no longer running for some reason. 

Soo back to my theory. The client has some previous work sitting in the que. On the server side the task or hashlist the client was working on has been removed or changed in some way. Causing problems. 

If you are having similar problems I would suggest wiping all files from your clients working directory ( do not remove  token, files, url )

**Comment by Thireus** [comment]
Thank you @winxp5421! You're indeed correct, this is when the server is under heavy load that this issue appears. I'll try to spot and clean the bad files on the client side if the issue persists, thanks for the advice.
