### ISSUE TITLE
Random pepper

### ISSUE THREAD

**Issue by NullPatrol** [s3inlc/hashtopussy#262]
Suggestion
On installation a thought could be to generate random peppers for the passwords, sessions and so on. Instead of the current static __PEPPER1__.
They could be stored in config for 'easier' access.

**Comment by s3inlc** [comment]
The installation script should create random generated peppers and place it instead of the placeholders.

Are you talking about the config on the database? Because if yes, this would reduce the security of the passwords, as when someone gains access to the database content he is able to crack the hashes. He then has hash, salt and pepper. If the pepper is only stored on the filesystem, a exposed db dump cannot be used to crack the hashes.

**Comment by NullPatrol** [comment]
Then that might have been me overwriting the encryption class there. No worries then ;)
