### ISSUE TITLE
template error

### ISSUE THREAD

**Issue by d2-d2** [s3inlc/hashtopussy#293]
It's for 0.4.2 release zip that can be downloaded from 'releases' tab.

inside **src/templates/hashlists/new.template.html** file there is a line
```
<option value="[[type.getId()]]"> [[type.getId()]] - [[htmlentities([[type.getDescription()]], ENT_QUOTES "UTF-8")]]</option>
```

and there is no comma after ENT_QUOTES statement which is causing following error:
```
PHP Parse error:  syntax error, unexpected '"UTF-8"' (T_CONSTANT_ENCAPSED_STRING), expecting ',' or ')' in /var/www/html/1/hashtopussy-0.4.2/src/inc/templating/Statement.class.php(181)
```

Mentioned line should be corrected to
```
<option value="[[type.getId()]]"> [[type.getId()]] - [[htmlentities([[type.getDescription()]], ENT_QUOTES, "UTF-8")]]</option>
```

It's already fixed in master, but since this bug is 'release' package, maybe you could upload fixed one?

**Comment by s3inlc** [comment]
Nearly always it's better to use the master branch than any release, as there might be smaller bugs like this which are fixed in the master branch.

I understand that it's not ideal to have such a typo in the release. As the zip is generated by Github itself it's a bit more complicated to just change it. I can see if it's just one commit later where it was fixed and then I can change it.

**Comment by s3inlc** [comment]
Unfortunately it's not easily possible to move the 0.4.2 release to some commits after the commit where it it's currently tagged as it's already a longer time since this release.

It would be possible for example to make a 0.4.3 version at the current master to make sure people are using the newer commits. Would this be good?

Currently I'm focussing more on getting time for the dev branch, the next release will then contain many changes to optimize some stuff and improve usability.

**Comment by d2-d2** [comment]
> It would be possible for example to make a 0.4.3 version at the current master to make sure people are using the newer commits. Would this be good?

Sure, I think that's fine. Or anything like 0.4.2-patch1 would be also fine. Just to indicate some change and provide working release.

Good to know the work is still going. Good luck with it. I am looking forward to test this new version when it will be available :)

**Comment by s3inlc** [comment]
Ok, then I'll go with this.

I'm trying to find the time to work on it as much as possible. But still will take some time until it's finished, there are a lot of things to adapt and change. You can keep an eye on the progress on the issues labeled with `dev`.

**Comment by s3inlc** [comment]
Release 0.4.3 is created, so I'll close this.
